<?xml version="1.0" ?><test><id>Test3</id><execution_id></execution_id><table name="Tests" file="C:/AXE_Projects/WebServiceTest/data/Tests.xml"/><description><![CDATA[try DB]]></description><start>2011/12/05 12:04:57 PM</start>
<subtest><index>1</index><id>Test01</id><table name="SQLUser" file="C:/AXE_Projects/WebServiceTest/data/Tests.xml"/><description><![CDATA[my database test]]></description><start>2011/12/05 12:04:57 PM</start>
<step><index>1</index><action>set</action><object>[]SQLUser</object><data><![CDATA[select * from accounts where Id = 1]]></data><start>2011/12/05 12:04:57 PM</start>
<info><![CDATA[A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)]]></info>
<finish>2011/12/05 12:05:14 PM</finish>
<time>17.06643</time>
<result>1</result>
<success>False</success>
</step>
<finish>2011/12/05 12:05:14 PM</finish>
<time>17.06643</time>
<result>Aborted</result>
<success>False</success>
<testcount>1</testcount>
<passcount>0</passcount>
<failcount>1</failcount>
</subtest>
<finish>2011/12/05 12:05:14 PM</finish>
<time>17.06643</time>
<result>Aborted</result>
<success>False</success>
<testcount>1</testcount>
<passcount>0</passcount>
<failcount>1</failcount>
</test>
